Change OnDropFiles() return values to integers
This prevents this error:
TypeError: invalid result from OOMMFSelectiveTarget.OnDropFiles(), an integer is required
Using standard stdin